/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#353437",
        "tertiary-fixed-dim": "#c7c5d0",
        "surface-tint": "#c6c6c7",
        "inverse-surface": "#e5e1e4",
        "surface-container": "#201f22",
        "on-error": "#690005",
        "tertiary-container": "#e3e1ec",
        "primary": "#ffffff",
        "secondary-fixed": "#e2e1eb",
        "surface": "#131315",
        "on-tertiary-fixed": "#1a1b23",
        "error": "#ffb4ab",
        "on-secondary-container": "#b4b4bd",
        "on-secondary": "#2f3037",
        "surface-container-highest": "#353437",
        "on-primary-fixed-variant": "#454747",
        "on-tertiary": "#2f3038",
        "error-container": "#93000a",
        "on-tertiary-container": "#64636d",
        "on-primary-container": "#636565",
        "primary-fixed": "#e2e2e2",
        "surface-bright": "#39393b",
        "on-secondary-fixed": "#1a1b22",
        "inverse-on-surface": "#313032",
        "surface-container-high": "#2a2a2c",
        "tertiary": "#ffffff",
        "primary-fixed-dim": "#c6c6c7",
        "surface-dim": "#131315",
        "outline-variant": "#444748",
        "tertiary-fixed": "#e3e1ec",
        "primary-container": "#e2e2e2",
        "surface-container-lowest": "#0e0e10",
        "secondary-fixed-dim": "#c6c6cf",
        "on-tertiary-fixed-variant": "#46464f",
        "surface-container-low": "#1c1b1d",
        "inverse-primary": "#5d5f5f",
        "on-error-container": "#ffdad6",
        "background": "#131315",
        "on-primary-fixed": "#1a1c1c",
        "secondary": "#c6c6cf",
        "on-secondary-fixed-variant": "#45464e",
        "on-primary": "#2f3131",
        "outline": "#8e9192",
        "on-surface": "#e5e1e4",
        "on-surface-variant": "#c4c7c8",
        "on-background": "#e5e1e4",
        "secondary-container": "#45464e"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "label-sm": ["JetBrains Mono"],
        "label-md": ["JetBrains Mono"],
        "display-lg": ["Geist"],
        "body-sm": ["Inter"],
        "headline-lg": ["Geist"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Geist"],
        "code": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
